branches:
  only:
    - master
os: osx
language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - git clone https://github.com/Homebrew/homebrew-cask-versions.git
  - node gen-cask.js > homebrew-cask-versions/Casks/safari-technology-preview.rb
  - echo DUMMY CHANGE > homebrew-cask-versions/Casks/safari-technology-preview.rb
  - cd homebrew-cask-versions
  #- git diff --quiet && travis_terminate 0 || : # stop if nothing has changed
after_success:
  - VERSION=TODO
  - BRANCH=safari-technology-preview-$VERSION
  - git checkout -b $BRANCH
  - git remote add autofoolip
  - git add -A
  - git config user.name "autofoolip"
  - git config user.email "auto@foolip.org"
  - git commit -m "Update safari-technology-preview to $VERSION" -m "https://travis-ci.com/foolip/safari-technology-preview-updater/builds/$TRAVIS_BUILD_ID"
  - git log -1
  - git push -f https://autofoolip:$GH_TOKEN@github.com/autofoolip/homebrew-cask-versions.git master $BRANCH
