jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'

  - script: npm install
    displayName: 'npm install'

  - script: git clone --depth 1 https://github.com/Homebrew/homebrew-cask-versions.git
    displayName: 'git clone homebrew-cask-versions'

  - script: node gen-cask.js > homebrew-cask-versions/Casks/safari-technology-preview.rb
    displayName: 'node gen-cask.js'

  - script: |
      cd homebrew-cask-versions
      if ! git diff --quiet; then
        echo "There are changes to safari-technology-preview.rb:"
        git diff
        echo "##vso[task.setvariable variable=changes]true"
      else
        echo "No changes to safari-technology-preview.rb"
        echo "##vso[task.setvariable variable=changes]true"
      fi
    displayName: 'check for changes'

  - script: brew cask audit --download homebrew-cask-versions/Casks/safari-technology-preview.rb
    displayName: 'brew cask audit'
    condition: and(succeeded(), variables.changes)

  - script: brew cask style homebrew-cask-versions/Casks/safari-technology-preview.rb
    displayName: 'brew cask style'
    condition: and(succeeded(), variables.changes)

  - script: HOMEBREW_NO_AUTO_UPDATE=1 brew cask install homebrew-cask-versions/Casks/safari-technology-preview.rb
    displayName: 'brew cask install'
    condition: and(succeeded(), variables.changes)

  - script: |
      "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --version
    displayName: 'safaridriver --version'
    condition: and(succeeded(), variables.changes)

  - script: |
      VERSION=TODO
      BRANCH=safari-technology-preview-$VERSION
      cd homebrew-cask-versions
      git fetch --unshallow
      git checkout -b $BRANCH
      git add -A
      git config user.name "autofoolip"
      git config user.email "auto@foolip.org"
      git commit -m "Update safari-technology-preview to $VERSION" -m "https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=$(Build.BuildId)"
      git log -1
      git push -f https://autofoolip:$(github.token)@github.com/autofoolip/homebrew-cask-versions.git master $BRANCH
    displayName: 'Push branch'
    condition: and(succeeded(), variables.changes)
