jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'

  - script: git clone https://github.com/Homebrew/homebrew-cask-versions.git

  - script: npm install

  - script: node gen-cask.js > homebrew-cask-versions/Casks/safari-technology-preview.rb

  - script: |
      cd homebrew-cask-versions
      git diff

# TODO push branch somewhere
# VERSION=TODO
# BRANCH=safari-technology-preview-$VERSION
# git checkout -b $BRANCH
# git remote add autofoolip
# git add -A
# git config user.name "autofoolip"
# git config user.email "auto@foolip.org"
# git commit -m "Update safari-technology-preview to $VERSION" -m "https://travis-ci.com/foolip/safari-technology-preview-updater/builds/$TRAVIS_BUILD_ID"
# git log -1
# git push -f https://autofoolip:$GH_TOKEN@github.com/autofoolip/homebrew-cask-versions.git master $BRANCH
