jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install dependencies'

  - script: git clone --depth 1 https://github.com/Homebrew/homebrew-cask-versions.git
    displayName: 'Clone homebrew-cask-versions'

  - script: node gen-cask.js > homebrew-cask-versions/Casks/safari-technology-preview.rb
    displayName: 'Update safari-technology-preview.rb'

  - script: |
      cd homebrew-cask-versions
      if ! git diff --quiet; then
        echo "There are changes to safari-technology-preview.rb:"
        git diff
        echo "##vso[task.setvariable variable=changes]true"
      else
        echo "No changes to safari-technology-preview.rb"
      fi
    displayName: 'Check for changes'

  - script: |
      VERSION=TODO
      BRANCH=safari-technology-preview-$VERSION
      cd homebrew-cask-versions
      git fetch --unshallow
      git checkout -b $BRANCH
      git add -A
      git config user.name "autofoolip"
      git config user.email "auto@foolip.org"
      git commit -m "Update safari-technology-preview to $VERSION" -m "https://dev.azure.com/foolip/safari-technology-preview-updater/_build/results?buildId=$(Build.BuildId)"
      git log -1
      git push -f https://autofoolip:$(github.token)@github.com/autofoolip/homebrew-cask-versions.git master $BRANCH
    displayName: 'Push branch'
    condition: variables.changes
